SET (CMAKE_C_COMPILER mpicc CACHE FILEPATH "Dummy comment" FORCE)
SET (CMAKE_C_FLAGS " -fPIC  -Wall -Wwrite-strings -Wno-strict-aliasing -Wno-unknown-pragmas -fstack-protector -fvisibility=hidden -g3 " CACHE STRING "Dummy comment" FORCE)
SET (PETSC_CUDA_HOST_FLAGS ,-fPIC,-Wall,-Wwrite-strings,-Wno-strict-aliasing,-Wno-unknown-pragmas,-fstack-protector,-fvisibility=hidden,-g3 CACHE STRING "Dummy comment" FORCE)
SET (CMAKE_Fortran_COMPILER mpif90 CACHE FILEPATH "Dummy comment" FORCE)
SET (CMAKE_Fortran_FLAGS " -fPIC -Wall -ffree-line-length-0 -Wno-unused-dummy-argument -g  " CACHE STRING "Dummy comment" FORCE)
SET (CMAKE_CXX_COMPILER mpicxx CACHE FILEPATH "Dummy comment" FORCE)
SET (CMAKE_CXX_FLAGS " -Wall -Wwrite-strings -Wno-strict-aliasing -Wno-unknown-pragmas -fstack-protector -fvisibility=hidden -g   -fPIC  " CACHE STRING "Dummy comment" FORCE)
SET (CMAKE_AR /usr/bin/ar CACHE FILEPATH "Dummy comment" FORCE)
SET (CMAKE_RANLIB /usr/bin/ranlib CACHE FILEPATH "Dummy comment" FORCE)
